services:
  miro-dialog:
    container_name: miro-dialog
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_IMAGE_TAG=${NODE_IMAGE_TAG:-21.5-bullseye-slim} # Node image tag
    ports:
      - ${FRONTEND_PORT:-3000}:3000
    volumes:
      - ./src:/app/src
      - /app/node_modules
